apiVersion: apps/v1
kind: Deployment
metadata:
  name: appweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appweb
  template:
    metadata:
      labels:
        app: appweb
    spec:
      containers:
        - name: appweb
          image: carrbrpoa/fullcycle-challenge3-app:k8s
          ports:
            - containerPort: 3001
